services:
  - type: web
    plan: free
    name: museo-web        # Nombre del servicio
    runtime: python
    buildCommand: |
      pip install -r requirements.txt  # Instalar las dependencias
      python manage.py collectstatic --noinput  # Ejecuta collectstatic para recopilar los archivos estáticos
    startCommand: "python -m gunicorn museo.asgi:application -k uvicorn.workers.UvicornWorker"  # Inicia el servidor
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4