services:
  - type: web
    plan: free
    name: museo-web        # Nombre del servicio
    runtime: python
    buildCommand: "pip install -r requirements.txt"  # Instalación de dependencias
    startCommand: "python -m gunicorn museo.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4