# Generated by Django 5.1.3 on 2024-11-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artista',
            fields=[
                ('id_artista', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_artista', models.CharField(max_length=100)),
                ('pais_artista', models.CharField(max_length=100)),
                ('ruta_artista', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='epoca',
            fields=[
                ('id_epoca', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_epoca', models.CharField(max_length=100)),
                ('anyos_epoca', models.CharField(max_length=100)),
                ('ruta_epoca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='museo',
            fields=[
                ('id_museo', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_museo', models.CharField(max_length=100)),
                ('pais_museo', models.CharField(max_length=100)),
                ('ruta_museo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='obras',
            fields=[
                ('id_obra', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_obra', models.CharField(max_length=100)),
                ('num_meGustas', models.IntegerField(default=0)),
                ('ruta_obra', models.CharField(max_length=100)),
                ('id_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.artista')),
                ('id_epoca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.epoca')),
                ('id_museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.museo')),
            ],
        ),
        migrations.CreateModel(
            name='favoritas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.obras')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.usuario')),
            ],
        ),
    ]
