# Generated by Django 5.1.3 on 2024-11-14 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_artista_biografia_artista_curiosidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='obrasArtista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.artista')),
                ('id_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.obras')),
            ],
        ),
    ]
