# Generated by Django 5.1.3 on 2024-11-16 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_obras_info_obrasartista'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='favoritas',
            new_name='favoritasObras',
        ),
        migrations.CreateModel(
            name='favoritasArtista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.artista')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='favoritasMuseos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_museo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.museo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.usuario')),
            ],
        ),
    ]
